---
# tasks/main.yml (percona-cluster-garbd)
# prefix : pxc_garbd

- name: Install tasks
  import_tasks: install.yml
  when:
    - pxc_garbd_install_flag | bool
  tags: ["install"]

- name: Configure tasks
  import_tasks: configure.yml
  tags: ["configure"]
  